import random
import numpy as np

RANDOM_SEED = random.random()

''' GA parmeters '''
POPULATION_SIZE = 4
MUTATION_RATE = 0
MAX_GENERATIONS = 100000
CROSSOVER_RATE = 0
TOURNAMENT_SIZE = 3

''' STRATEGY PARAMETERS '''
MIN_TIME_HORIZON = 1
MAX_TIME_HORIZON = 10

''' MARKET PARAMETERS '''
TRADING_DAYS = 252

MIN_WEALTH = 10
MAX_WEALTH = 10

INITIAL_PRICE = 1

REINVESTMENT_RATE = 1
INTEREST_RATE = 0.01 / TRADING_DAYS

EMA_HORIZON = 20 #252

# DIVIDEND_GROWTH_RATE = 0.02 / TRADING_DAYS
DIVIDEND_GROWTH_RATE_G = 0.02
DIVIDEND_GROWTH_VOLATILITY = 0.06 / np.sqrt(TRADING_DAYS)
DIVIDEND_AUTOCORRELATION = 0.1 
INITIAL_DIVIDEND = 0.01
INITIAL_RANDOM_DIVIDEND = 0
DIVIDEND_ATC_TAU = 3

''' RESULTS STORAGE '''
dividend_history = []
random_dividend_history = []
