import random

RANDOM_SEED = random.random()
POPULATION_SIZE = 4
MAX_TIME_HORIZON = 10
MUTATION_RATE = 0
MAX_GENERATIONS = 10
CROSSOVER_RATE = 0
MIN_WEALTH = 10
MAX_WEALTH = 10
MIN_TIME_HORIZON = 1
INITIAL_PRICE = 1
TOURNAMENT_SIZE = 3

REINVESTMENT_RATE = 1
INTEREST_RATE = 0.1

EMA_HORIZON = 20 #252