sns.heatmap(gaussian_filter(dataNT,sigma=sigma), ax=ax1, cmap = cmap)
sns.heatmap(gaussian_filter(dataVI,sigma=sigma), ax=ax2, cmap = cmap)
sns.heatmap(gaussian_filter(dataTF,sigma=sigma), ax=ax3, cmap = cmap)
ax1.set_yticklabels(model.get_yticklabels(), rotation = 0)
ax2.set_yticklabels(model.get_yticklabels(), rotation = 0)
ax3.set_yticklabels(model.get_yticklabels(), rotation = 0)
ax1.set_xticklabels(model.get_xticklabels(), rotation = 90)
ax2.set_xticklabels(model.get_xticklabels(), rotation = 90)
ax3.set_xticklabels(model.get_xticklabels(), rotation = 90)